sudo: false
language: dart
dart:
  - dev
  - stable

install:
  - gem install coveralls-lcov
  - pub get
  - pub global activate dart_coveralls

script:
  - pub run test
  - pub global run dart_coveralls report --token $COVERALLS_TOKEN --retry 2 --exclute-test-files test/all.dart

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.pub-cache
