name: logger
description: A simple, yet efficient structured logger for Dart.
version: 0.2.0
author: Roman Vanesyan <romain.vanesyan@gmail.com>
homepage: https://github.com/vanesyan/logger.dart
environment:
  sdk: '>2.0.0-dev <=3.0.0'
